spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: siuki
    url: jdbc:mysql://localhost:3306/exchangeRate
    password: Ssw0304!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8080'
